-- ============================================
-- Migration 019: Verify Password Hashes
-- ============================================
-- Description: Updates demo user password hashes to ensure compatibility
--              with the @node-rs/argon2 library used by the frontend.
--
-- This migration ensures production hashes match those generated by:
--   cd frontend && npx tsx scripts/generate-password-hashes.ts
--
-- Author: Claude Code
-- Date: 2026-01-09
-- Dependencies: 016_seed_demo_users.sql
--
-- Usage:
--   psql nba_stats < migrations/019_verify_password_hashes.sql
-- ============================================

-- Update admin password hash
-- Password: Admin123!
UPDATE users SET
    password_hash = '$argon2id$v=19$m=65536,t=3,p=4$EY+SXQQZ3KOY0n51cUIlAQ$j64zXBTlZ0VoAwqD/VloE3QkhWuqRm2wirSxAisvmYI',
    updated_at = NOW(),
    failed_login_attempts = 0,
    locked_until = NULL
WHERE email = 'admin@stat-discute.be';

-- Update demo password hash
-- Password: Demo123!
UPDATE users SET
    password_hash = '$argon2id$v=19$m=65536,t=3,p=4$5+2uhaKVOfAviHMsDK/kYA$qgLd7tG8c4qdFyWDaX57gCO2E9FcKV1wSvE0OxF+lYo',
    updated_at = NOW(),
    failed_login_attempts = 0,
    locked_until = NULL
WHERE email = 'demo@stat-discute.be';

-- ============================================
-- VERIFICATION
-- ============================================

DO $$
DECLARE
    admin_hash TEXT;
    demo_hash TEXT;
BEGIN
    SELECT password_hash INTO admin_hash FROM users WHERE email = 'admin@stat-discute.be';
    SELECT password_hash INTO demo_hash FROM users WHERE email = 'demo@stat-discute.be';

    RAISE NOTICE '================================================';
    RAISE NOTICE 'Migration 019: Verify Password Hashes - COMPLETE';
    RAISE NOTICE '================================================';
    RAISE NOTICE 'Admin hash updated: %', SUBSTRING(admin_hash FROM 1 FOR 50) || '...';
    RAISE NOTICE 'Demo hash updated: %', SUBSTRING(demo_hash FROM 1 FOR 50) || '...';
    RAISE NOTICE '';
    RAISE NOTICE 'Demo accounts ready:';
    RAISE NOTICE '  - admin@stat-discute.be (Admin123!)';
    RAISE NOTICE '  - demo@stat-discute.be (Demo123!)';
    RAISE NOTICE '================================================';
END $$;

-- Show updated users
SELECT
    email,
    SUBSTRING(password_hash FROM 1 FOR 50) || '...' as hash_prefix,
    failed_login_attempts,
    locked_until,
    updated_at
FROM users
WHERE email IN ('admin@stat-discute.be', 'demo@stat-discute.be')
ORDER BY email;
